// resources/js/Pages/Samples/Index.vue
<template>
    <Layout>
        <div class="flex justify-between items-center mb-6">
            <div>
                <h1 class="text-2xl font-bold text-gray-900">样品管理</h1>
                <p class="mt-1 text-sm text-gray-500">查看和管理所有检测样品</p>
            </div>
            <Link
                v-if="$page.props.auth.user.role === 'sampler' || $page.props.auth.user.role === 'reviewer'"
                :href="route('samples.create')"
                class="inline-flex items-center px-4 py-2 bg-green-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-700 active:bg-green-900 focus:outline-none focus:border-green-900 focus:ring focus:ring-green-300 disabled:opacity-25 transition"
            >
                新增样品
            </Link>
        </div>

        <div class="bg-white shadow rounded-lg p-6 mb-6">
            <form @submit.prevent="search" class="flex gap-4 items-end">
                <div class="flex-1">
                    <label class="block text-sm font-medium text-gray-700 mb-1">搜索</label>
                    <input
                        v-model="form.search"
                        type="text"
                        placeholder="样品编号、产品名称、产地..."
                        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-green-500 focus:border-green-500"
                    />
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">状态</label>
                    <select
                        v-model="form.status"
                        class="px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-green-500 focus:border-green-500"
                    >
                        <option value="">全部状态</option>
                        <option value="registered">已登记</option>
                        <option value="testing">检测中</option>
                        <option value="qualified">合格</option>
                        <option value="unqualified">不合格</option>
                        <option value="processing">处置中</option>
                        <option value="reinspection_applied">复检申请中</option>
                        <option value="returned">已退回</option>
                        <option value="archived">已归档</option>
                    </select>
                </div>
                <button type="submit" class="px-4 py-2 bg-gray-800 text-white rounded-md hover:bg-gray-700">
                    搜索
                </button>
            </form>
        </div>

        <div class="bg-white shadow rounded-lg overflow-hidden">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">样品编号</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">产品名称</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">产地</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">抽样员</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">状态</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">操作</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    <tr v-for="sample in samples.data" :key="sample.id" :class="{ 'bg-red-50': sample.conflict_sample_id }">
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="text-sm font-medium text-gray-900">{{ sample.sample_number }}</div>
                            <div v-if="sample.conflict_sample_id" class="text-xs text-red-600">存在编号冲突</div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="text-sm text-gray-900">{{ sample.product_name }}</div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="text-sm text-gray-500">{{ sample.origin }}</div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="text-sm text-gray-500">{{ sample.sampler?.name }}</div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <StatusBadge :status="sample.status" />
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                            <Link :href="route('samples.show', sample.id)" class="text-green-600 hover:text-green-900">查看</Link>
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="px-6 py-4 bg-gray-50 border-t border-gray-200">
                <div class="flex justify-between items-center">
                    <span class="text-sm text-gray-700">共 {{ samples.total }} 条记录</span>
                    <div class="flex gap-2">
                        <button
                            v-if="samples.prev_page_url"
                            @click="changePage(samples.current_page - 1)"
                            class="px-3 py-1 border border-gray-300 rounded-md text-sm hover:bg-gray-50"
                        >
                            上一页
                        </button>
                        <button
                            v-if="samples.next_page_url"
                            @click="changePage(samples.current_page + 1)"
                            class="px-3 py-1 border border-gray-300 rounded-md text-sm hover:bg-gray-50"
                        >
                            下一页
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </Layout>
</template>

<script setup>
import { ref } from 'vue';
import { router, useForm, Link } from '@inertiajs/vue3';
import Layout from '../../Components/Layout.vue';
import StatusBadge from '../../Components/StatusBadge.vue';

const props = defineProps({
    samples: Object,
    filters: Object,
});

const form = useForm({
    search: props.filters.search || '',
    status: props.filters.status || '',
});

const search = () => {
    router.get(route('samples.index'), form.data(), { preserveState: true });
};

const changePage = (page) => {
    router.get(route('samples.index'), { ...form.data(), page }, { preserveState: true });
};
</script>

// src/app/samples/page.tsx
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { getSampleList } from "@/lib/actions/sample-actions";
import { StatusBadge } from "@/components/StatusBadge";
import Link from "next/link";
import { formatDate } from "@/lib/utils";
import { Plus, Search, Filter, FlaskConical } from "lucide-react";
import type { SampleStatus } from "@prisma/client";

interface SamplesPageProps {
  searchParams: Promise<{
    status?: string;
    port?: string;
    search?: string;
  }>;
}

export default async function SamplesPage({ searchParams }: SamplesPageProps) {
  const session = await auth();
  if (!session?.user) {
    redirect("/login");
  }

  const params = await searchParams;
  const samples = await getSampleList({
    status: params.status as SampleStatus | undefined,
    port: params.port,
    search: params.search,
  });

  const statusOptions: { value: SampleStatus | ""; label: string }[] = [
    { value: "", label: "全部状态" },
    { value: "SAMPLING", label: "待取样" },
    { value: "SAMPLED", label: "已取样" },
    { value: "SENT_TO_LAB", label: "已送检" },
    { value: "TESTING", label: "检测中" },
    { value: "PENDING_DISPOSAL", label: "待处置" },
    { value: "DISPOSED", label: "已处置" },
    { value: "RE_SAMPLING", label: "需重取" },
    { value: "ARCHIVED", label: "已归档" },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">样品管理</h1>
          <p className="text-slate-500 mt-1">查看和管理所有查验样品</p>
        </div>
        {session.user.role === "INSPECTION_OFFICER" && (
          <Link
            href="/samples/new"
            className="inline-flex items-center px-4 py-2 bg-customs-600 hover:bg-customs-700 text-white font-medium rounded-lg transition-colors"
          >
            <Plus className="w-5 h-5 mr-2" />
            新建取样
          </Link>
        )}
      </div>

      <div className="bg-white rounded-xl border border-slate-200">
        <div className="p-4 border-b border-slate-200 flex flex-wrap gap-4 items-center">
          <form className="flex items-center gap-2 flex-1 min-w-[300px]">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
              <input
                type="text"
                name="search"
                defaultValue={params.search}
                placeholder="搜索样品编号、报关单、货物名称..."
                className="w-full pl-10 pr-4 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-customs-500 focus:border-customs-500 outline-none"
              />
            </div>
          </form>
          <div className="flex items-center gap-2">
            <Filter className="w-4 h-4 text-slate-400" />
            <select
              name="status"
              defaultValue={params.status || ""}
              className="px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-customs-500 focus:border-customs-500 outline-none"
            >
              {statusOptions.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-slate-50">
              <tr className="text-left text-sm text-slate-600">
                <th className="px-5 py-3 font-medium">样品编号</th>
                <th className="px-5 py-3 font-medium">报关单号</th>
                <th className="px-5 py-3 font-medium">货物名称</th>
                <th className="px-5 py-3 font-medium">商品类别</th>
                <th className="px-5 py-3 font-medium">口岸</th>
                <th className="px-5 py-3 font-medium">封签状态</th>
                <th className="px-5 py-3 font-medium">样品状态</th>
                <th className="px-5 py-3 font-medium">当前责任人</th>
                <th className="px-5 py-3 font-medium">创建时间</th>
                <th className="px-5 py-3 font-medium">操作</th>
              </tr>
            </thead>
            <tbody className="text-sm divide-y divide-slate-100">
              {samples.map((sample) => (
                <tr key={sample.id} className="hover:bg-slate-50">
                  <td className="px-5 py-4">
                    <Link
                      href={`/samples/${sample.id}`}
                      className="text-customs-600 hover:text-customs-700 font-medium"
                    >
                      {sample.sampleNo}
                    </Link>
                  </td>
                  <td className="px-5 py-4 text-slate-700">
                    {sample.customsDeclarationNo}
                  </td>
                  <td className="px-5 py-4 text-slate-700">{sample.goodsName}</td>
                  <td className="px-5 py-4 text-slate-600">
                    {sample.goodsCategory}
                  </td>
                  <td className="px-5 py-4 text-slate-600">{sample.port}</td>
                  <td className="px-5 py-4">
                    {sample.seals.length > 0 && (
                      <StatusBadge
                        status={sample.seals[0].status}
                        type="seal"
                      />
                    )}
                  </td>
                  <td className="px-5 py-4">
                    <StatusBadge status={sample.status} type="sample" />
                  </td>
                  <td className="px-5 py-4 text-slate-600">
                    {sample.currentHandler?.name || "-"}
                  </td>
                  <td className="px-5 py-4 text-slate-500">
                    {formatDate(sample.createdAt)}
                  </td>
                  <td className="px-5 py-4">
                    <Link
                      href={`/samples/${sample.id}`}
                      className="text-customs-600 hover:text-customs-700"
                    >
                      查看详情
                    </Link>
                  </td>
                </tr>
              ))}
              {samples.length === 0 && (
                <tr>
                  <td colSpan={10} className="px-5 py-12 text-center">
                    <div className="flex flex-col items-center">
                      <FlaskConical className="w-12 h-12 text-slate-300 mb-3" />
                      <p className="text-slate-500">暂无样品数据</p>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
