// resources/js/Pages/WasteBatches/Create.jsx
import { Head, useForm, Link } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { useState } from 'react';

export default function Create({ categories, locations }) {
    const { data, setData, post, processing, errors } = useForm({
        waste_category_id: '',
        storage_location_id: '',
        weight: '',
        description: '',
        production_date: new Date().toISOString().split('T')[0],
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post(route('waste-batches.store'));
    };

    return (
        <AuthenticatedLayout
            header={
                <h2 className="text-xl font-semibold leading-tight text-gray-800">
                    危废暂存登记
                </h2>
            }
        >
            <Head title="危废暂存登记" />

            <div className="py-12">
                <div className="max-w-3xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                        <form onSubmit={handleSubmit} className="p-6 space-y-6">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    危废类别
                                </label>
                                <select
                                    value={data.waste_category_id}
                                    onChange={(e) => setData('waste_category_id', e.target.value)}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                >
                                    <option value="">请选择危废类别</option>
                                    {categories.map((category) => (
                                        <option key={category.id} value={category.id}>
                                            {category.code} - {category.name} (限制: {category.max_weight_per_batch}kg)
                                        </option>
                                    ))}
                                </select>
                                {errors.waste_category_id && (
                                    <p className="mt-1 text-sm text-red-600">{errors.waste_category_id}</p>
                                )}
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    暂存位置
                                </label>
                                <select
                                    value={data.storage_location_id}
                                    onChange={(e) => setData('storage_location_id', e.target.value)}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                >
                                    <option value="">请选择暂存位置</option>
                                    {locations.map((location) => (
                                        <option key={location.id} value={location.id}>
                                            {location.code} - {location.name}
                                        </option>
                                    ))}
                                </select>
                                {errors.storage_location_id && (
                                    <p className="mt-1 text-sm text-red-600">{errors.storage_location_id}</p>
                                )}
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    重量 (kg)
                                </label>
                                <input
                                    type="number"
                                    step="0.01"
                                    value={data.weight}
                                    onChange={(e) => setData('weight', e.target.value)}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                    placeholder="请输入重量"
                                />
                                {errors.weight && (
                                    <p className="mt-1 text-sm text-red-600">{errors.weight}</p>
                                )}
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    产生日期
                                </label>
                                <input
                                    type="date"
                                    value={data.production_date}
                                    onChange={(e) => setData('production_date', e.target.value)}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                />
                                {errors.production_date && (
                                    <p className="mt-1 text-sm text-red-600">{errors.production_date}</p>
                                )}
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    备注说明
                                </label>
                                <textarea
                                    value={data.description}
                                    onChange={(e) => setData('description', e.target.value)}
                                    rows={3}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                    placeholder="请输入备注说明（可选）"
                                />
                            </div>

                            <div className="flex justify-end space-x-4">
                                <Link
                                    href={route('waste-batches.index')}
                                    className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50"
                                >
                                    取消
                                </Link>
                                <button
                                    type="submit"
                                    disabled={processing}
                                    className="px-4 py-2 bg-green-600 border border-transparent rounded-md font-medium text-white hover:bg-green-700 disabled:opacity-50"
                                >
                                    提交登记
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/Disposals/Create.vue
<template>
    <Layout>
        <div class="mb-6">
            <h1 class="text-2xl font-bold text-gray-900">创建处置建议</h1>
            <p class="mt-1 text-sm text-gray-500">{{ sample.sample_number }} - {{ sample.product_name }}</p>
        </div>

        <div v-if="!sample.canBeDisposed" class="mb-6 p-4 bg-red-50 border border-red-200 rounded-md">
            <p class="text-red-700">
                {{ sample.conflict_note || '样品当前状态不允许处置' }}
            </p>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div class="space-y-6">
                <div class="bg-white shadow rounded-lg p-6">
                    <h2 class="text-lg font-medium text-gray-900 mb-4">样品信息</h2>
                    <div class="space-y-3">
                        <div class="flex justify-between">
                            <span class="text-gray-500">样品编号</span>
                            <span class="font-medium">{{ sample.sample_number }}</span>
                        </div>
                        <div class="flex justify-between">
                            <span class="text-gray-500">产品名称</span>
                            <span class="font-medium">{{ sample.product_name }}</span>
                        </div>
                        <div class="flex justify-between">
                            <span class="text-gray-500">产地</span>
                            <span class="font-medium">{{ sample.origin }}</span>
                        </div>
                        <div class="flex justify-between">
                            <span class="text-gray-500">批次号</span>
                            <span class="font-medium">{{ sample.batch_number }}</span>
                        </div>
                    </div>
                </div>

                <div v-if="sample.inspection_result" class="bg-white shadow rounded-lg p-6">
                    <h2 class="text-lg font-medium text-gray-900 mb-4">检测结果</h2>
                    <div class="mb-3">
                        <span :class="sample.inspection_result.result === 'qualified' ? 'text-green-600' : 'text-red-600'" class="font-medium">
                            {{ sample.inspection_result.result === 'qualified' ? '合格' : sample.inspection_result.result === 'pesticide_exceeded' ? '农残超标' : '其他不合格' }}
                        </span>
                    </div>
                    <p class="text-sm text-gray-600">{{ sample.inspection_result.conclusion }}</p>
                </div>
            </div>

            <div class="bg-white shadow rounded-lg p-6">
                <form @submit.prevent="submit" class="space-y-6">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">处置动作 *</label>
                        <select
                            v-model="form.action"
                            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-green-500 focus:border-green-500"
                        >
                            <option v-for="action in actions" :key="action.value" :value="action.value">
                                {{ action.label }}
                            </option>
                        </select>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">处置建议 *</label>
                        <textarea
                            v-model="form.suggestion"
                            rows="5"
                            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-green-500 focus:border-green-500"
                            placeholder="请输入详细的处置建议..."
                        ></textarea>
                    </div>

                    <div class="flex justify-end gap-4">
                        <Link :href="route('samples.show', sample.id)" class="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50">
                            取消
                        </Link>
                        <button
                            type="submit"
                            :disabled="processing || !sample.canBeDisposed"
                            class="px-4 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700 disabled:opacity-50"
                        >
                            <span v-if="processing">提交中...</span>
                            <span v-else>提交处置建议</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </Layout>
</template>

<script setup>
import { useForm, Link } from '@inertiajs/vue3';
import Layout from '../../Components/Layout.vue';

const props = defineProps({
    sample: Object,
    actions: Array,
});

const form = useForm({
    action: 'destroy',
    suggestion: '',
});

const submit = () => {
    form.post(route('disposals.store', props.sample.id));
};

const { processing } = form;
</script>
