// resources/js/Pages/Login.vue
<template>
  <div class="min-h-screen bg-gray-100 flex items-center justify-center">
    <div class="bg-white rounded-lg shadow-lg p-8 w-full max-w-md">
      <h2 class="text-2xl font-bold text-center text-gray-800 mb-6">门店巡检系统</h2>
      <form @submit.prevent="login">
        <div class="mb-4">
          <label class="block text-gray-700 text-sm font-medium mb-2">邮箱</label>
          <input
            v-model="form.email"
            type="email"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="请输入邮箱"
          />
        </div>
        <div class="mb-6">
          <label class="block text-gray-700 text-sm font-medium mb-2">密码</label>
          <input
            v-model="form.password"
            type="password"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="请输入密码"
          />
        </div>
        <button
          type="submit"
          class="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition-colors"
          :disabled="loading"
        >
          {{ loading ? '登录中...' : '登录' }}
        </button>
      </form>
      <div v-if="error" class="mt-4 p-3 bg-red-100 text-red-700 rounded-lg text-center">
        {{ error }}
      </div>
      <div class="mt-4 text-center text-gray-500 text-sm">
        <p>督导: supervisor@example.com / 123456</p>
        <p>店长: store_manager@example.com / 123456</p>
        <p>区域经理: region_manager@example.com / 123456</p>
        <p>运营负责人: operation@example.com / 123456</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue';

const form = reactive({
  email: '',
  password: ''
});

const loading = ref(false);
const error = ref('');

const login = async () => {
  loading.value = true;
  error.value = '';
  
  try {
    const response = await window.axios.post('/api/login', form);
    localStorage.setItem('token', response.data.token);
    localStorage.setItem('user', JSON.stringify(response.data.user));
    window.axios.defaults.headers.common['Authorization'] = `Bearer ${response.data.token}`;
    window.location.href = '/dashboard';
  } catch (e) {
    error.value = e.response?.data?.error || '登录失败';
  } finally {
    loading.value = false;
  }
};
</script>

// frontend/src/routes/login/index.tsx
import { component$, useContext, useStore, $ } from '@builder.io/qwik';
import { useNavigate } from '@builder.io/qwik-city';
import { Layout } from '~/components/layout/layout';
import { Loading } from '~/components/ui/loading';
import { AppStore } from '~/constants';
import { fetchApi } from '~/utils/api';
import type { User } from '~/types';

export default component$(() => {
  const store = useContext(AppStore);
  const nav = useNavigate();
  const form = useStore({
    username: '',
    password: '',
    error: '',
  });

  const handleLogin = $(async () => {
    if (!form.username || !form.password) {
      form.error = '请输入用户名和密码';
      return;
    }

    try {
      store.isLoading = true;
      form.error = '';
      
      const response = await fetchApi<{ user: User; token: string }>('/login', {
        method: 'POST',
        body: JSON.stringify({ username: form.username, password: form.password }),
      });

      store.currentUser = response.user;
      if (typeof window !== 'undefined') {
        localStorage.setItem('currentUser', JSON.stringify(response.user));
      }
      nav('/');
    } catch (e) {
      form.error = '用户名或密码错误';
    } finally {
      store.isLoading = false;
    }
  });

  return (
    <Layout>
      <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-antique-50 to-antique-100 p-4">
        <div class="card w-full max-w-md">
          <div class="text-center mb-8">
            <div class="text-5xl mb-4">📜</div>
            <h1 class="text-2xl font-bold text-antique-900">古籍修复馆</h1>
            <p class="text-gray-500 mt-2">纸张病害诊断与修复排程系统</p>
          </div>

          {form.error && (
            <div class="mb-4 p-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
              {form.error}
            </div>
          )}

          <div class="space-y-4">
            <div>
              <label class="label">用户名</label>
              <input
                type="text"
                class="input"
                placeholder="请输入用户名"
                value={form.username}
                onInput$={(_, el) => (form.username = el.value)}
                onKeyDown$={(e) => e.key === 'Enter' && handleLogin()}
              />
            </div>
            <div>
              <label class="label">密码</label>
              <input
                type="password"
                class="input"
                placeholder="请输入密码"
                value={form.password}
                onInput$={(_, el) => (form.password = el.value)}
                onKeyDown$={(e) => e.key === 'Enter' && handleLogin()}
              />
            </div>
            <button
              class="btn btn-primary w-full"
              onClick$={handleLogin}
              disabled={store.isLoading}
            >
              {store.isLoading ? <Loading size="sm" /> : '登录'}
            </button>
          </div>

          <div class="mt-6 pt-6 border-t text-sm text-gray-500">
            <p class="mb-2 font-medium">测试账号：</p>
            <ul class="space-y-1 text-xs">
              <li>修复师：zhanggxf / 123456</li>
              <li>管理员：wanggly / 123456</li>
              <li>专家：chenzj / 123456</li>
            </ul>
          </div>
        </div>
      </div>
    </Layout>
  );
});
