// src/pages/Kanban.tsx
import { useNavigate } from 'react-router-dom'
import { useApi } from '@/hooks/useApi'
import LoadingSpinner from '@/components/LoadingSpinner'
import ErrorState from '@/components/ErrorState'
import type { InterlibraryRequest } from '@/types'

const columns = [
  { key: 'pending', label: '待审批', statuses: ['pending'], color: 'bg-gray-400' },
  { key: 'approved_shipping', label: '已批准/待寄出', statuses: ['approved', 'shipping_out'], color: 'bg-cyan-400' },
  { key: 'in_transit', label: '运输中', statuses: ['in_transit'], color: 'bg-amber-400' },
  { key: 'arrived_reading', label: '到馆/借阅', statuses: ['arrived', 'reading'], color: 'bg-green-400' },
  { key: 'renewal', label: '续借中', statuses: ['renewal_pending', 'renewal_approved'], color: 'bg-purple-400' },
  { key: 'overdue_exception', label: '逾期/异常', statuses: ['overdue', 'exception'], color: 'bg-red-400' },
  { key: 'return_completed', label: '归还/完成', statuses: ['returning', 'completed'], color: 'bg-slate-400' },
]

const formatDate = (d: string) => {
  const dt = new Date(d)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${dt.getFullYear()}-${pad(dt.getMonth() + 1)}-${pad(dt.getDate())} ${pad(dt.getHours())}:${pad(dt.getMinutes())}`
}

export default function Kanban() {
  const navigate = useNavigate()
  const { data: requests, loading, error, refetch } = useApi<InterlibraryRequest[]>('/api/requests')

  if (loading) return <LoadingSpinner text="加载看板数据..." />
  if (error) return <ErrorState message={error} onRetry={refetch} />

  const filtered = (requests || []).filter(
    (r) => r.status !== 'rejected' && r.status !== 'renewal_rejected'
  )

  const grouped = columns.map((col) => ({
    ...col,
    items: filtered.filter((r) => col.statuses.includes(r.status)),
  }))

  return (
    <div className="h-full flex flex-col">
      <h1 className="text-xl font-semibold text-slate-800 mb-4">馆际流转看板</h1>
      <div className="flex gap-4 overflow-x-auto pb-4 flex-1">
        {grouped.map((col) => (
          <div key={col.key} className="flex-shrink-0 flex flex-col" style={{ width: 280 }}>
            <div className="flex items-center gap-2 mb-3 px-1">
              <span className="font-medium text-slate-700 text-sm">{col.label}</span>
              <span className="inline-flex items-center justify-center w-5 h-5 rounded-full bg-slate-200 text-xs font-medium text-slate-600">
                {col.items.length}
              </span>
            </div>
            <div className="space-y-2 flex-1 overflow-y-auto">
              {col.items.map((req) => (
                <div
                  key={req.id}
                  onClick={() => navigate(`/requests/${req.id}`)}
                  className="bg-white rounded-lg shadow-sm cursor-pointer hover:shadow-md transition-shadow overflow-hidden"
                >
                  <div className={`h-[3px] ${col.color}`} />
                  <div className="p-3 space-y-1.5">
                    <p className="text-xs text-slate-400 font-mono">{req.request_no}</p>
                    <p className="text-sm font-semibold text-slate-800 line-clamp-1">{req.title}</p>
                    <p className="text-xs text-slate-500">
                      {req.reader_name} · {req.library_name || '-'}
                    </p>
                    <p className="text-xs text-slate-400">{formatDate(req.created_at)}</p>
                  </div>
                </div>
              ))}
              {col.items.length === 0 && (
                <div className="text-center py-6 text-xs text-slate-400">暂无</div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// src/routes/kanban.tsx
import { A } from "@solidjs/router";
import { createAsync } from "@solidjs/router";
import { For } from "solid-js";
import StatusBadge from "~/components/StatusBadge";
import { getILLRequestsAction } from "~/server/actions";
import type { ILLRequestDetail, ILLRequestStatus } from "~/server/db";

const columns: { status: ILLRequestStatus; label: string; color: string }[] = [
  { status: "pending", label: "待匹配", color: "border-yellow-400" },
  { status: "matched", label: "已匹配", color: "border-blue-400" },
  { status: "approved", label: "已审批", color: "border-indigo-400" },
  { status: "shipped", label: "运输中", color: "border-purple-400" },
  { status: "received", label: "已到馆", color: "border-cyan-400" },
  { status: "lending", label: "借阅中", color: "border-green-400" },
  { status: "overdue", label: "已逾期", color: "border-red-400" }
];

export default function Kanban() {
  const requests = createAsync(() => getILLRequestsAction());

  const getRequestsByStatus = (status: ILLRequestStatus) => {
    return requests()?.filter((r: ILLRequestDetail) => r.status === status) || [];
  };

  return (
    <div class="space-y-6">
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-2xl font-bold text-gray-900 mb-2">馆际流转看板</h1>
          <p class="text-gray-500">实时查看馆际互借的流转状态</p>
        </div>
        <A href="/requests/new" class="btn-primary">
          ➕ 新建申请
        </A>
      </div>

      <div class="overflow-x-auto">
        <div class="flex gap-4 min-w-max pb-4">
          <For each={columns}>
            {(column) => {
              const columnRequests = getRequestsByStatus(column.status);
              return (
                <div class="w-72 flex-shrink-0">
                  <div class={`bg-white rounded-xl border-t-4 ${column.color} shadow-sm`}>
                    <div class="p-4 border-b border-gray-100">
                      <div class="flex items-center justify-between">
                        <h3 class="font-semibold text-gray-900">{column.label}</h3>
                        <span class="badge bg-gray-100 text-gray-600">
                          {columnRequests.length}
                        </span>
                      </div>
                    </div>
                    <div class="p-3 space-y-3 max-h-[calc(100vh-300px)] overflow-y-auto">
                      {columnRequests.length === 0 ? (
                        <div class="text-center py-8 text-gray-400 text-sm">
                          暂无任务
                        </div>
                      ) : (
                        <For each={columnRequests}>
                          {(req: ILLRequestDetail) => (
                            <A
                              href={`/requests/${req.id}`}
                              class="block p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                            >
                              <div class="flex items-start justify-between mb-2">
                                <span class="font-mono text-xs text-primary-600">{req.request_no}</span>
                                <StatusBadge status={req.status} />
                              </div>
                              <h4 class="font-medium text-gray-900 text-sm line-clamp-2 mb-1">
                                {req.book_title}
                              </h4>
                              <p class="text-xs text-gray-500 mb-2">{req.book_author}</p>
                              <div class="flex items-center justify-between text-xs text-gray-400">
                                <span>👤 {req.reader_name}</span>
                                <span>{req.request_date}</span>
                              </div>
                            </A>
                          )}
                        </For>
                      )}
                    </div>
                  </div>
                </div>
              );
            }}
          </For>
        </div>
      </div>
    </div>
  );
}
