// src/components/Header.tsx
"use client";

import { User, LogOut } from "lucide-react";
import { signOut } from "next-auth/react";
import type { UserRole } from "@prisma/client";

interface HeaderProps {
  user: {
    id: string;
    username: string;
    name: string;
    role: UserRole;
    department?: string | null;
    employeeId?: string | null;
  };
}

export default function Header({ user }: HeaderProps) {
  const roleLabels: Record<UserRole, string> = {
    INSPECTION_OFFICER: "查验关员",
    LAB_TECHNICIAN: "实验室人员",
    DISPOSAL_REVIEWER: "处置复核人",
  };

  return (
    <header className="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-6">
      <div>
        <h2 className="text-lg font-semibold text-slate-800">
          欢迎回来，{user.name}
        </h2>
        <p className="text-sm text-slate-500">
          {roleLabels[user.role]}
          {user.department && ` · ${user.department}`}
        </p>
      </div>
      <div className="flex items-center space-x-4">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 rounded-full bg-customs-100 flex items-center justify-center">
            <User className="w-5 h-5 text-customs-600" />
          </div>
          <div className="text-right">
            <p className="text-sm font-medium text-slate-800">{user.name}</p>
            <p className="text-xs text-slate-500">{user.username}</p>
          </div>
        </div>
        <button
          onClick={() => signOut()}
          className="p-2 text-slate-500 hover:text-slate-700 hover:bg-slate-100 rounded-lg transition-colors"
          title="退出登录"
        >
          <LogOut className="w-5 h-5" />
        </button>
      </div>
    </header>
  );
}

// frontend/src/components/layout/header.tsx
import { component$ } from '@builder.io/qwik';
import { useAuth } from '~/context/auth';
import { User, ChevronDown } from 'lucide-qwik';
import type { UserRole } from '~/types';
import { UserRoleLabels } from '~/types';

export const Header = component$(() => {
  const { state, switchRole } = useAuth();

  return (
    <header class="bg-white border-b border-gray-200 px-6 py-4">
      <div class="flex justify-between items-center">
        <div>
          <h2 class="text-lg font-semibold text-gray-800">欢迎回来，{state.currentUserName}</h2>
          <p class="text-sm text-gray-500">当前角色: {UserRoleLabels[state.currentRole as UserRole]}</p>
        </div>
        
        <div class="flex items-center space-x-4">
          <div class="relative group">
            <button class="flex items-center space-x-2 px-4 py-2 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors">
              <User class="w-5 h-5 text-gray-600" />
              <span class="text-gray-700">切换角色</span>
              <ChevronDown class="w-4 h-4 text-gray-500" />
            </button>
            <div class="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-gray-200 hidden group-hover:block z-10">
              {(['cold_chain_admin', 'cdc_reviewer', 'vaccination_site_manager'] as UserRole[]).map((role) => (
                <button
                  key={role}
                  onClick$={() => switchRole(role)}
                  class={`w-full text-left px-4 py-3 hover:bg-gray-50 transition-colors ${
                    state.currentRole === role ? 'bg-primary-50 text-primary-600' : 'text-gray-700'
                  }`}
                >
                  {UserRoleLabels[role]}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </header>
  );
});
