// src/components/header.tsx
import { RoleSwitcher } from "./role-switcher";
import { Bell, Search } from "lucide-react";

export function Header() {
  return (
    <header className="flex h-16 items-center justify-between border-b border-gray-200 bg-white px-6">
      <div className="flex items-center gap-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            placeholder="搜索缺陷..."
            className="h-9 w-80 rounded-lg border border-gray-200 bg-gray-50 pl-10 pr-4 text-sm placeholder-gray-400 focus:border-amber-400 focus:outline-none focus:ring-2 focus:ring-amber-100"
          />
        </div>
      </div>

      <div className="flex items-center gap-4">
        <button className="relative rounded-lg p-2 text-gray-500 hover:bg-gray-100 transition-colors">
          <Bell className="h-5 w-5" />
          <span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-red-500"></span>
        </button>
        <RoleSwitcher />
      </div>
    </header>
  );
}

// frontend/src/components/layout/header.tsx
import { component$ } from '@builder.io/qwik';
import { useAuth } from '~/context/auth';
import { User, ChevronDown } from 'lucide-qwik';
import type { UserRole } from '~/types';
import { UserRoleLabels } from '~/types';

export const Header = component$(() => {
  const { state, switchRole } = useAuth();

  return (
    <header class="bg-white border-b border-gray-200 px-6 py-4">
      <div class="flex justify-between items-center">
        <div>
          <h2 class="text-lg font-semibold text-gray-800">欢迎回来，{state.currentUserName}</h2>
          <p class="text-sm text-gray-500">当前角色: {UserRoleLabels[state.currentRole as UserRole]}</p>
        </div>
        
        <div class="flex items-center space-x-4">
          <div class="relative group">
            <button class="flex items-center space-x-2 px-4 py-2 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors">
              <User class="w-5 h-5 text-gray-600" />
              <span class="text-gray-700">切换角色</span>
              <ChevronDown class="w-4 h-4 text-gray-500" />
            </button>
            <div class="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-gray-200 hidden group-hover:block z-10">
              {(['cold_chain_admin', 'cdc_reviewer', 'vaccination_site_manager'] as UserRole[]).map((role) => (
                <button
                  key={role}
                  onClick$={() => switchRole(role)}
                  class={`w-full text-left px-4 py-3 hover:bg-gray-50 transition-colors ${
                    state.currentRole === role ? 'bg-primary-50 text-primary-600' : 'text-gray-700'
                  }`}
                >
                  {UserRoleLabels[role]}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </header>
  );
});
