// client/src/components/layout/Layout.tsx
import React from 'react';
import { Outlet } from 'react-router-dom';
import Sidebar from './Sidebar';

export const Layout: React.FC = () => {
  return (
    <div className="flex h-screen bg-gray-50">
      <Sidebar />
      <main className="flex-1 overflow-hidden flex flex-col">
        <div className="flex-1 overflow-y-auto scrollbar-thin">
          <Outlet />
        </div>
      </main>
    </div>
  );
};

export default Layout;

// frontend/src/components/layout/index.tsx
import { component$, Slot } from '@builder.io/qwik';
import { Sidebar } from './sidebar';
import { Header } from './header';

export const Layout = component$(() => {
  return (
    <div class="flex min-h-screen">
      <Sidebar />
      <div class="flex-1 flex flex-col">
        <Header />
        <main class="flex-1 p-6 overflow-auto">
          <Slot />
        </main>
      </div>
    </div>
  );
});
