// src/components/Sidebar.tsx
import { useLocation, Link } from 'react-router-dom';
import { ClipboardCheck, BarChart3 } from 'lucide-react';

const navItems = [
  { href: '/', label: '异常核对', icon: ClipboardCheck },
  { href: '/review', label: '复盘统计', icon: BarChart3 },
];

export default function Sidebar() {
  const location = useLocation();

  return (
    <nav className="fixed top-0 left-0 bottom-0 w-60 bg-slate-900 text-white flex flex-col z-50">
      <div className="px-6 py-5 border-b border-slate-700">
        <h1 className="text-base font-bold tracking-tight">餐卡充值异常</h1>
        <p className="text-xs text-slate-400 mt-0.5">退款核对系统</p>
      </div>
      <div className="flex-1 py-4">
        {navItems.map((item) => {
          const isActive =
            item.href === '/'
              ? location.pathname === '/' || location.pathname.startsWith('/detail')
              : location.pathname === item.href;
          return (
            <Link
              key={item.href}
              to={item.href}
              className={`flex items-center gap-3 px-6 py-3 text-sm transition-colors ${
                isActive
                  ? 'bg-amber-500/15 text-amber-400 border-r-2 border-amber-400'
                  : 'text-slate-300 hover:bg-slate-800 hover:text-white'
              }`}
            >
              <item.icon size={16} strokeWidth={1.5} />
              {item.label}
            </Link>
          );
        })}
      </div>
      <div className="px-6 py-4 border-t border-slate-700">
        <p className="text-xs text-slate-500">园区财务管理平台</p>
      </div>
    </nav>
  );
}

// frontend/src/components/layout/sidebar.tsx
import { component$ } from '@builder.io/qwik';
import { Link, useLocation } from '@builder.io/qwik-city';
import { useAuth } from '~/context/auth';
import {
  LayoutDashboard,
  ThermometerSnowflake,
  Package,
  Truck,
  ClipboardCheck,
  RotateCcw,
  FileBarChart,
  Users,
} from 'lucide-qwik';

interface NavItem {
  label: string;
  path: string;
  icon: any;
  roles: string[];
}

const navItems: NavItem[] = [
  { label: '仪表盘', path: '/', icon: LayoutDashboard, roles: ['cold_chain_admin', 'cdc_reviewer', 'vaccination_site_manager'] },
  { label: '冷库台账', path: '/cold-storages', icon: ThermometerSnowflake, roles: ['cold_chain_admin'] },
  { label: '转运箱管理', path: '/transport-boxes', icon: Truck, roles: ['cold_chain_admin'] },
  { label: '温控偏差', path: '/deviations', icon: ThermometerSnowflake, roles: ['cold_chain_admin', 'cdc_reviewer'] },
  { label: '批次隔离', path: '/quarantine', icon: Package, roles: ['cold_chain_admin'] },
  { label: '复核放行', path: '/review', icon: ClipboardCheck, roles: ['cdc_reviewer'] },
  { label: '召回协同', path: '/recall', icon: RotateCcw, roles: ['cdc_reviewer', 'vaccination_site_manager'] },
  { label: '追溯报表', path: '/trace', icon: FileBarChart, roles: ['cold_chain_admin', 'cdc_reviewer'] },
  { label: '接种点库存', path: '/inventory', icon: Package, roles: ['vaccination_site_manager', 'cdc_reviewer'] },
];

export const Sidebar = component$(() => {
  const location = useLocation();
  const { state } = useAuth();

  const filteredNavItems = navItems.filter(item => 
    item.roles.includes(state.currentRole)
  );

  return (
    <aside class="w-64 bg-white border-r border-gray-200 min-h-screen flex flex-col">
      <div class="p-6 border-b border-gray-200">
        <h1 class="text-xl font-bold text-primary-600">疫苗冷链系统</h1>
        <p class="text-sm text-gray-500 mt-1">县域疾控中心</p>
      </div>
      
      <nav class="flex-1 p-4 space-y-1">
        {filteredNavItems.map((item) => {
          const isActive = location.url.pathname === item.path;
          const Icon = item.icon;
          return (
            <Link
              key={item.path}
              href={item.path}
              class={`flex items-center px-4 py-3 rounded-lg transition-colors ${
                isActive
                  ? 'bg-primary-50 text-primary-600 font-medium'
                  : 'text-gray-600 hover:bg-gray-50'
              }`}
            >
              <Icon class="w-5 h-5 mr-3" />
              {item.label}
            </Link>
          );
        })}
      </nav>
    </aside>
  );
});
