// frontend/src/components/layout/sidebar.tsx
import { component$ } from '@builder.io/qwik';
import { Link, useLocation } from '@builder.io/qwik-city';
import { useAuth } from '~/context/auth';
import {
  LayoutDashboard,
  ThermometerSnowflake,
  Package,
  Truck,
  ClipboardCheck,
  RotateCcw,
  FileBarChart,
  Users,
} from 'lucide-qwik';

interface NavItem {
  label: string;
  path: string;
  icon: any;
  roles: string[];
}

const navItems: NavItem[] = [
  { label: '仪表盘', path: '/', icon: LayoutDashboard, roles: ['cold_chain_admin', 'cdc_reviewer', 'vaccination_site_manager'] },
  { label: '冷库台账', path: '/cold-storages', icon: ThermometerSnowflake, roles: ['cold_chain_admin'] },
  { label: '转运箱管理', path: '/transport-boxes', icon: Truck, roles: ['cold_chain_admin'] },
  { label: '温控偏差', path: '/deviations', icon: ThermometerSnowflake, roles: ['cold_chain_admin', 'cdc_reviewer'] },
  { label: '批次隔离', path: '/quarantine', icon: Package, roles: ['cold_chain_admin'] },
  { label: '复核放行', path: '/review', icon: ClipboardCheck, roles: ['cdc_reviewer'] },
  { label: '召回协同', path: '/recall', icon: RotateCcw, roles: ['cdc_reviewer', 'vaccination_site_manager'] },
  { label: '追溯报表', path: '/trace', icon: FileBarChart, roles: ['cold_chain_admin', 'cdc_reviewer'] },
  { label: '接种点库存', path: '/inventory', icon: Package, roles: ['vaccination_site_manager', 'cdc_reviewer'] },
];

export const Sidebar = component$(() => {
  const location = useLocation();
  const { state } = useAuth();

  const filteredNavItems = navItems.filter(item => 
    item.roles.includes(state.currentRole)
  );

  return (
    <aside class="w-64 bg-white border-r border-gray-200 min-h-screen flex flex-col">
      <div class="p-6 border-b border-gray-200">
        <h1 class="text-xl font-bold text-primary-600">疫苗冷链系统</h1>
        <p class="text-sm text-gray-500 mt-1">县域疾控中心</p>
      </div>
      
      <nav class="flex-1 p-4 space-y-1">
        {filteredNavItems.map((item) => {
          const isActive = location.url.pathname === item.path;
          const Icon = item.icon;
          return (
            <Link
              key={item.path}
              href={item.path}
              class={`flex items-center px-4 py-3 rounded-lg transition-colors ${
                isActive
                  ? 'bg-primary-50 text-primary-600 font-medium'
                  : 'text-gray-600 hover:bg-gray-50'
              }`}
            >
              <Icon class="w-5 h-5 mr-3" />
              {item.label}
            </Link>
          );
        })}
      </nav>
    </aside>
  );
});

// app/components/Sidebar.tsx
import { Link, useLocation } from "@remix-run/react";
import {
  LayoutDashboard,
  Building2,
  Elevator,
  ClipboardList,
  AlertTriangle,
  Kanban,
  FileWarning,
  Settings,
} from "lucide-react";

interface SidebarProps {
  currentPath: string;
}

const menuItems = [
  { path: "/", label: "仪表盘", icon: LayoutDashboard },
  { path: "/elevators", label: "电梯管理", icon: Elevator },
  { path: "/plans", label: "维保计划", icon: ClipboardList },
  { path: "/faults", label: "故障管理", icon: AlertTriangle },
  { path: "/kanban", label: "统计看板", icon: Kanban },
];

export function Sidebar({ currentPath }: SidebarProps) {
  return (
    <aside className="fixed left-0 top-0 h-screen w-64 bg-slate-900 text-white flex flex-col">
      <div className="p-6 border-b border-slate-700">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-primary rounded-lg flex items-center justify-center">
            <Elevator className="w-6 h-6" />
          </div>
          <div>
            <h1 className="font-semibold text-lg">电梯维保</h1>
            <p className="text-xs text-slate-400">管理系统</p>
          </div>
        </div>
      </div>

      <nav className="flex-1 p-4">
        <ul className="space-y-1">
          {menuItems.map((item) => {
            const Icon = item.icon;
            const isActive = currentPath === item.path ||
              (item.path !== "/" && currentPath.startsWith(item.path));

            return (
              <li key={item.path}>
                <Link
                  to={item.path}
                  className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-colors ${
                    isActive
                      ? "bg-primary text-white"
                      : "text-slate-300 hover:bg-slate-800 hover:text-white"
                  }`}
                >
                  <Icon className="w-5 h-5" />
                  <span>{item.label}</span>
                </Link>
              </li>
            );
          })}
        </ul>
      </nav>

      <div className="p-4 border-t border-slate-700">
        <div className="flex items-center gap-3 px-4 py-3 text-slate-400">
          <Settings className="w-5 h-5" />
          <span className="text-sm">系统设置</span>
        </div>
        <div className="mt-4 px-4">
          <div className="text-xs text-slate-500">当前用户</div>
          <div className="text-sm font-medium">物业管理员</div>
        </div>
      </div>
    </aside>
  );
}
