// frontend/src/components/ui/loading.tsx
import { component$ } from '@builder.io/qwik';

interface LoadingProps {
  size?: 'sm' | 'md' | 'lg';
  text?: string;
}

export const Loading = component$<LoadingProps>(({ size = 'md', text = '加载中...' }) => {
  const sizeClasses = {
    sm: 'w-4 h-4',
    md: 'w-8 h-8',
    lg: 'w-12 h-12',
  };

  return (
    <div class="flex flex-col items-center justify-center p-8">
      <div class={`${sizeClasses[size]} border-2 border-antique-200 border-t-antique-600 rounded-full spinner`} />
      {text && <p class="mt-3 text-gray-500">{text}</p>}
    </div>
  );
});

export const PageLoading = component$(() => (
  <div class="min-h-[400px] flex items-center justify-center">
    <Loading size="lg" />
  </div>
));

// client/src/components/common/Loading.tsx
import React from 'react';

interface LoadingProps {
  size?: 'sm' | 'md' | 'lg';
  text?: string;
  fullPage?: boolean;
}

export const Loading: React.FC<LoadingProps> = ({ size = 'md', text, fullPage = false }) => {
  const sizeClasses = {
    sm: 'w-4 h-4',
    md: 'w-8 h-8',
    lg: 'w-12 h-12',
  };

  const content = (
    <div className="flex flex-col items-center justify-center gap-3">
      <div
        className={`${sizeClasses[size]} border-4 border-gray-200 border-t-primary-600 rounded-full animate-spin`}
      />
      {text && <p className="text-gray-500 text-sm">{text}</p>}
    </div>
  );

  if (fullPage) {
    return (
      <div className="fixed inset-0 bg-white bg-opacity-80 flex items-center justify-center z-50">
        {content}
      </div>
    );
  }

  return content;
};

export default Loading;
