// app/components/Layout.tsx
import { Form, NavLink } from "@remix-run/react";
import type { Role } from "@prisma/client";

interface LayoutProps {
  user: { id: string; email: string; name: string; role: Role };
  children: React.ReactNode;
}

const roleLabels: Record<Role, string> = {
  CONSULTANT: "顾问",
  CLIENT: "客户",
  AGENT: "代理人",
  SUPERVISOR: "主管",
};

export default function Layout({ user, children }: LayoutProps) {
  const navItems = getNavItems(user.role);

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex">
              <div className="flex-shrink-0 flex items-center">
                <span className="text-xl font-bold text-blue-600">商标续展系统</span>
              </div>
              <div className="hidden sm:ml-6 sm:flex sm:space-x-8">
                {navItems.map((item) => (
                  <NavLink
                    key={item.to}
                    to={item.to}
                    end={item.end}
                    className={({ isActive }) =>
                      `inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium ${
                        isActive
                          ? "border-blue-500 text-gray-900"
                          : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"
                      }`
                    }
                  >
                    {item.label}
                  </NavLink>
                ))}
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <div className="text-sm">
                <span className="text-gray-700 font-medium">{user.name}</span>
                <span className="ml-2 text-gray-500">({roleLabels[user.role]})</span>
              </div>
              <Form action="/logout" method="post">
                <button
                  type="submit"
                  className="text-gray-500 hover:text-gray-700 text-sm font-medium"
                >
                  退出登录
                </button>
              </Form>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        {children}
      </main>
    </div>
  );
}

function getNavItems(role: Role): { to: string; label: string; end?: boolean }[] {
  const base = [
    { to: "/", label: "首页", end: true },
  ];

  switch (role) {
    case "CONSULTANT":
      return [
        ...base,
        { to: "/trademarks", label: "商标管理" },
        { to: "/analytics", label: "数据复盘" },
      ];
    case "CLIENT":
      return [
        ...base,
        { to: "/trademarks", label: "我的商标" },
      ];
    case "AGENT":
      return [
        ...base,
        { to: "/trademarks", label: "审核队列" },
        { to: "/analytics", label: "数据复盘" },
      ];
    case "SUPERVISOR":
      return [
        ...base,
        { to: "/trademarks", label: "复核队列" },
        { to: "/analytics", label: "数据复盘" },
      ];
    default:
      return base;
  }
}

// resources/js/Components/Layout.vue
<template>
    <div class="min-h-screen bg-gray-100">
        <nav class="bg-white border-b border-gray-200">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="flex justify-between h-16">
                    <div class="flex">
                        <div class="flex-shrink-0 flex items-center">
                            <span class="text-xl font-bold text-green-600">农产品检测系统</span>
                        </div>
                        <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                            <Link :href="route('dashboard')" class="inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" :class="route().current('dashboard') ? 'border-green-500 text-gray-900' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'">
                                首页
                            </Link>
                            <Link :href="route('samples.index')" class="inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" :class="route().current('samples.*') ? 'border-green-500 text-gray-900' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'">
                                样品管理
                            </Link>
                            <Link v-if="$page.props.auth.user.role === 'sampler' || $page.props.auth.user.role === 'inspector' || $page.props.auth.user.role === 'reviewer'" :href="route('inspections.index')" class="inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" :class="route().current('inspections.*') ? 'border-green-500 text-gray-900' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'">
                                检测管理
                            </Link>
                            <Link v-if="$page.props.auth.user.role === 'reviewer'" :href="route('disposals.index')" class="inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" :class="route().current('disposals.*') ? 'border-green-500 text-gray-900' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'">
                                处置管理
                            </Link>
                            <Link :href="route('reinspections.index')" class="inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" :class="route().current('reinspections.*') ? 'border-green-500 text-gray-900' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'">
                                复检申请
                            </Link>
                            <Link :href="route('review.index')" class="inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" :class="route().current('review.*') ? 'border-green-500 text-gray-900' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'">
                                复盘查询
                            </Link>
                        </div>
                    </div>
                    <div class="hidden sm:flex sm:items-center sm:ml-6">
                        <div class="ml-3 relative">
                            <div class="flex items-center space-x-4">
                                <span class="text-sm text-gray-500">{{ $page.props.auth.user.name }}</span>
                                <span class="px-2 py-1 text-xs bg-green-100 text-green-800 rounded">{{ $page.props.auth.user.role_name }}</span>
                                <form @submit.prevent="logout">
                                    <button type="submit" class="text-sm text-gray-500 hover:text-gray-700">退出</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <main class="py-6">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div v-if="$page.props.flash.success" class="mb-4 p-4 bg-green-100 border border-green-400 text-green-700 px-4 rounded">
                    {{ $page.props.flash.success }}
                </div>
                <div v-if="$page.props.flash.error" class="mb-4 p-4 bg-red-100 border border-red-400 text-red-700 px-4 rounded">
                    {{ $page.props.flash.error }}
                </div>
                <slot />
            </div>
        </main>
    </div>
</template>

<script setup>
import { Link, router } from '@inertiajs/vue3';

const logout = () => {
    router.post(route('logout'));
};
</script>
