// src/components/StatusBadge.tsx
interface StatusBadgeProps {
  status: string;
}

const statusConfig: Record<string, { label: string; className: string }> = {
  pending: { label: '待审批', className: 'bg-yellow-100 text-yellow-800 border-yellow-300' },
  approved: { label: '已审批', className: 'bg-blue-100 text-blue-800 border-blue-300' },
  rejected: { label: '已驳回', className: 'bg-red-100 text-red-800 border-red-300' },
  checked_in: { label: '已签到', className: 'bg-green-100 text-green-800 border-green-300' },
  checked_out: { label: '已签退', className: 'bg-gray-100 text-gray-800 border-gray-300' },
  timeout: { label: '超时未离', className: 'bg-orange-100 text-orange-800 border-orange-300' },
  cancelled: { label: '已取消', className: 'bg-gray-100 text-gray-800 border-gray-300' },
};

export default function StatusBadge({ status }: StatusBadgeProps) {
  const config = statusConfig[status] || { label: status, className: 'bg-gray-100 text-gray-800 border-gray-300' };

  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${config.className}`}>
      {config.label}
    </span>
  );
}

// resources/js/Components/StatusBadge.vue
<template>
  <span
    :class="[
      'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
      badgeClass
    ]"
  >
    <span v-if="hasBlocking" class="w-2 h-2 bg-red-500 rounded-full mr-1 animate-pulse"></span>
    <span v-if="isArchived" class="w-2 h-2 bg-green-500 rounded-full mr-1"></span>
    {{ label }}
  </span>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
  status: {
    type: String,
    required: true
  },
  hasBlocking: {
    type: Boolean,
    default: false
  },
  isArchived: {
    type: Boolean,
    default: false
  }
});

const statusLabels = {
  accepted: '已受理',
  processing: '处理中',
  reviewing: '复核中',
  approved: '已通过',
  archived: '已归档',
  returned: '已退回',
  appealed: '申诉中',
  number_conflict: '编号冲突',
  amount_difference: '金额差异'
};

const statusColors = {
  accepted: 'bg-blue-100 text-blue-800',
  processing: 'bg-yellow-100 text-yellow-800',
  reviewing: 'bg-purple-100 text-purple-800',
  approved: 'bg-teal-100 text-teal-800',
  archived: 'bg-green-100 text-green-800',
  returned: 'bg-red-100 text-red-800',
  appealed: 'bg-orange-100 text-orange-800',
  number_conflict: 'bg-red-100 text-red-800',
  amount_difference: 'bg-red-100 text-red-800'
};

const label = computed(() => statusLabels[props.status] || props.status);
const badgeClass = computed(() => statusColors[props.status] || 'bg-gray-100 text-gray-800');
</script>
