// app/components/Layout.tsx
import { Link, NavLink, useLocation } from "react-router";
import { useState } from "react";
import { USER_ROLE_LABELS, type UserRole } from "~/lib/utils";

interface LayoutProps {
  children: React.ReactNode;
  currentRole: UserRole;
  onRoleChange: (role: UserRole) => void;
}

export function Layout({ children, currentRole, onRoleChange }: LayoutProps) {
  const location = useLocation();

  const navItems = [
    { to: "/permits", label: "施工许可", icon: "📋" },
    { to: "/permits/new", label: "新建申请", icon: "➕" },
    { to: "/statistics", label: "复盘统计", icon: "📊" },
  ];

  const roles: UserRole[] = ["SECURITY_OFFICER", "ENGINEERING_MANAGER", "SAFETY_REVIEWER"];

  return (
    <div className="min-h-screen bg-slate-50 flex">
      <aside className="w-64 bg-slate-900 text-white flex flex-col">
        <div className="p-6 border-b border-slate-800">
          <h1 className="text-xl font-bold text-white flex items-center gap-2">
            <span className="text-2xl">🏗️</span>
            <span>园区施工管理</span>
          </h1>
          <p className="text-slate-400 text-sm mt-1">访客施工许可平台</p>
        </div>

        <nav className="flex-1 p-4 space-y-1">
          {navItems.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              end={item.to === "/permits"}
              className={({ isActive }) =>
                `flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-all ${
                  isActive
                    ? "bg-primary-600 text-white shadow-lg shadow-primary-600/30"
                    : "text-slate-300 hover:bg-slate-800 hover:text-white"
                }`
              }
            >
              <span className="text-lg">{item.icon}</span>
              {item.label}
            </NavLink>
          ))}
        </nav>

        <div className="p-4 border-t border-slate-800">
          <p className="text-xs text-slate-500 mb-2 uppercase tracking-wider">当前角色</p>
          <div className="space-y-1">
            {roles.map((role) => (
              <button
                key={role}
                onClick={() => onRoleChange(role)}
                className={`w-full text-left px-3 py-2 rounded-md text-sm transition-all ${
                  currentRole === role
                    ? "bg-slate-800 text-white font-medium"
                    : "text-slate-400 hover:text-white hover:bg-slate-800/50"
                }`}
              >
                {USER_ROLE_LABELS[role]}
                {currentRole === role && <span className="ml-2 text-primary-400">●</span>}
              </button>
            ))}
          </div>
        </div>
      </aside>

      <main className="flex-1 flex flex-col overflow-hidden">
        <header className="bg-white border-b border-slate-200 px-8 py-4 flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-slate-800">
              {currentRole === "SECURITY_OFFICER" && "安保经办工作台"}
              {currentRole === "ENGINEERING_MANAGER" && "工程管理工作台"}
              {currentRole === "SAFETY_REVIEWER" && "安全复核工作台"}
            </h2>
            <p className="text-sm text-slate-500">
              {USER_ROLE_LABELS[currentRole]}视角
            </p>
          </div>
          <div className="flex items-center gap-3">
            <div className="text-right">
              <p className="text-sm font-medium text-slate-700">
                {currentRole === "SECURITY_OFFICER" && "张安保"}
                {currentRole === "ENGINEERING_MANAGER" && "李工程"}
                {currentRole === "SAFETY_REVIEWER" && "王安全"}
              </p>
              <p className="text-xs text-slate-500">{USER_ROLE_LABELS[currentRole]}</p>
            </div>
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary-500 to-primary-700 flex items-center justify-center text-white font-semibold">
              {currentRole === "SECURITY_OFFICER" && "张"}
              {currentRole === "ENGINEERING_MANAGER" && "李"}
              {currentRole === "SAFETY_REVIEWER" && "王"}
            </div>
          </div>
        </header>

        <div className="flex-1 overflow-auto p-8">{children}</div>
      </main>
    </div>
  );
}

// src/components/Layout.tsx
import { Component, ParentProps, children as Children, createMemo } from "solid-js";
import { A, useLocation } from "@solidjs/router";
import { useDatabase, getAnomalies } from "~/lib/database";

const navItems = [
  { path: "/", label: "工作台", icon: "📊" },
  { path: "/ledger", label: "项目台账", icon: "📋" },
  { path: "/map", label: "导览地图", icon: "🗺️" },
  { path: "/inspections", label: "巡检任务", icon: "✅" },
  { path: "/versions", label: "版本历史", icon: "📜" },
  { path: "/exports", label: "导出记录", icon: "📤" }
];

const Layout: Component<ParentProps> = (props) => {
  const location = useLocation();
  const { state } = useDatabase();
  const anomalies = createMemo(() => getAnomalies());
  const c = Children(() => props.children);

  const totalEntities = () => {
    const s = state();
    return s.channels.length + s.entrances.length + s.signs.length +
           s.equipment.length + s.maps.length + s.inspections.length;
  };

  return (
    <div class="min-h-screen flex bg-slate-100">
      <aside class="w-64 bg-slate-900 text-white flex flex-col fixed h-full">
        <div class="p-6 border-b border-slate-700">
          <h1 class="text-lg font-bold flex items-center gap-2">
            <span class="text-2xl">🏛️</span>
            <div>
              <div>人防空间</div>
              <div class="text-xs text-slate-400 font-normal">导览维护系统</div>
            </div>
          </h1>
        </div>

        <nav class="flex-1 p-4 space-y-1 overflow-y-auto">
          {navItems.map(item => (
            <A
              href={item.path}
              class={`flex items-center gap-3 px-4 py-2.5 rounded-lg transition-all ${
                location.pathname === item.path
                  ? "bg-primary-600 text-white"
                  : "text-slate-300 hover:bg-slate-800 hover:text-white"
              }`}
            >
              <span class="text-lg">{item.icon}</span>
              <span class="font-medium">{item.label}</span>
              {item.path === "/ledger" && (
                <span class="ml-auto text-xs bg-slate-700 px-2 py-0.5 rounded-full">
                  {totalEntities()}
                </span>
              )}
              {item.path === "/" && anomalies().length > 0 && (
                <span class="ml-auto text-xs bg-danger-500 px-2 py-0.5 rounded-full">
                  {anomalies().length}
                </span>
              )}
            </A>
          ))}
        </nav>

        <div class="p-4 border-t border-slate-700">
          <div class="text-xs text-slate-400">
            <div>当前批次: {state().currentBatchId}</div>
            <div class="mt-1">最后更新: {new Date().toLocaleDateString("zh-CN")}</div>
          </div>
        </div>
      </aside>

      <main class="flex-1 ml-64">
        <header class="bg-white border-b border-gray-200 sticky top-0 z-10">
          <div class="px-8 py-4 flex items-center justify-between">
            <div>
              <h2 class="text-xl font-semibold text-gray-800">
                {navItems.find(n => n.path === location.pathname)?.label || "系统"}
              </h2>
              <p class="text-sm text-gray-500">
                城市地下人防空间数字化管理平台
              </p>
            </div>
            <div class="flex items-center gap-4">
              {anomalies().length > 0 && (
                <A href="/" class="flex items-center gap-2 px-4 py-2 bg-danger-50 text-danger-600 rounded-lg hover:bg-danger-100 transition-colors">
                  <span>⚠️</span>
                  <span class="text-sm font-medium">{anomalies().length} 项异常待处理</span>
                </A>
              )}
              <div class="flex items-center gap-3">
                <div class="w-9 h-9 rounded-full bg-primary-100 text-primary-700 flex items-center justify-center font-semibold">
                  管
                </div>
                <div class="text-sm">
                  <div class="font-medium text-gray-800">管理员</div>
                  <div class="text-xs text-gray-500">system@cdms.gov</div>
                </div>
              </div>
            </div>
          </div>
        </header>

        <div class="p-8">
          {c()}
        </div>
      </main>
    </div>
  );
};

export default Layout;
