// src/components/Loading.tsx
interface LoadingProps {
  size?: 'sm' | 'md' | 'lg'
  text?: string
}

export default function Loading({ size = 'md', text = '加载中...' }: LoadingProps) {
  const sizeClasses = {
    sm: 'w-4 h-4 border-2',
    md: 'w-6 h-6 border-2',
    lg: 'w-10 h-10 border-3',
  }

  return (
    <div className="flex items-center justify-center gap-3">
      <div className={`loader ${sizeClasses[size]}`}></div>
      {text && <span className="text-gray-500">{text}</span>}
    </div>
  )
}

export function LoadingPage({ text = '加载中...' }: { text?: string }) {
  return (
    <div className="flex items-center justify-center min-h-[400px]">
      <Loading size="lg" text={text} />
    </div>
  )
}

export function LoadingCard() {
  return (
    <div className="card p-6">
      <div className="animate-pulse">
        <div className="h-4 bg-gray-200 rounded w-1/4 mb-4"></div>
        <div className="h-8 bg-gray-200 rounded w-1/2 mb-6"></div>
        <div className="space-y-3">
          <div className="h-4 bg-gray-200 rounded"></div>
          <div className="h-4 bg-gray-200 rounded w-5/6"></div>
          <div className="h-4 bg-gray-200 rounded w-4/6"></div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/components/ui/loading.tsx
import { component$ } from '@builder.io/qwik';

interface LoadingProps {
  size?: 'sm' | 'md' | 'lg';
  text?: string;
}

export const Loading = component$<LoadingProps>(({ size = 'md', text = '加载中...' }) => {
  const sizeClasses = {
    sm: 'w-4 h-4',
    md: 'w-8 h-8',
    lg: 'w-12 h-12',
  };

  return (
    <div class="flex flex-col items-center justify-center p-8">
      <div class={`${sizeClasses[size]} border-2 border-antique-200 border-t-antique-600 rounded-full spinner`} />
      {text && <p class="mt-3 text-gray-500">{text}</p>}
    </div>
  );
});

export const PageLoading = component$(() => (
  <div class="min-h-[400px] flex items-center justify-center">
    <Loading size="lg" />
  </div>
));
