// src/components/layout/Layout.tsx
import { Outlet, Link } from 'react-router-dom'
import { FileText, BarChart3, Menu, X } from 'lucide-react'
import { useState } from 'react'

export function DefaultLayout() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center">
                <FileText className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-lg font-bold text-gray-900">质量索赔平台</h1>
                <p className="text-xs text-gray-500">汽车零部件质量索赔与供应商扣款</p>
              </div>
            </div>

            <nav className="hidden md:flex items-center gap-6">
              <Link
                to="/"
                className="flex items-center gap-2 text-gray-600 hover:text-blue-600 transition-colors"
              >
                <FileText className="w-4 h-4" />
                <span>索赔列表</span>
              </Link>
              <Link
                to="/report"
                className="flex items-center gap-2 text-gray-600 hover:text-blue-600 transition-colors"
              >
                <BarChart3 className="w-4 h-4" />
                <span>数据复盘</span>
              </Link>
            </nav>

            <button
              className="md:hidden p-2 text-gray-600"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
            </button>
          </div>
        </div>

        {mobileMenuOpen && (
          <div className="md:hidden bg-white border-t border-gray-200">
            <nav className="px-4 py-4 space-y-2">
              <Link
                to="/"
                className="block px-4 py-2 text-gray-600 hover:bg-gray-50 rounded-lg"
                onClick={() => setMobileMenuOpen(false)}
              >
                索赔列表
              </Link>
              <Link
                to="/report"
                className="block px-4 py-2 text-gray-600 hover:bg-gray-50 rounded-lg"
                onClick={() => setMobileMenuOpen(false)}
              >
                数据复盘
              </Link>
            </nav>
          </div>
        )}
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Outlet />
      </main>
    </div>
  )
}

// resources/js/Shared/Layout.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <header class="bg-white shadow-sm border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <div class="flex items-center space-x-3">
            <div class="w-10 h-10 bg-primary-500 rounded-lg flex items-center justify-center">
              <ClipboardList class="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 class="text-xl font-bold text-gray-800">商户装修审批系统</h1>
              <p class="text-sm text-gray-500">围挡审批与消防材料复核</p>
            </div>
          </div>
          <nav class="flex items-center space-x-1">
            <button
              v-for="item in navItems"
              :key="item.path"
              @click="$inertia.visit(item.path)"
              class="px-4 py-2 rounded-lg text-sm font-medium transition-all"
              :class="currentPath === item.path ? 'bg-primary-100 text-primary-700' : 'text-gray-600 hover:bg-gray-100'"
            >
              <component :is="item.icon" class="w-5 h-5 inline-block mr-2" />
              {{ item.label }}
            </button>
          </nav>
        </div>
      </div>
    </header>
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <slot />
    </main>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { ClipboardList, LayoutDashboard, FileText, KanbanSquare } from 'lucide-vue-next'

defineProps({
  title: String
})

const currentPath = ref(window.location.pathname)

const navItems = [
  { path: '/', label: '仪表盘', icon: LayoutDashboard },
  { path: '/applications', label: '申请列表', icon: FileText },
  { path: '/kanban', label: '看板统计', icon: KanbanSquare },
]
</script>
