// app/routes/login.tsx
import { useState } from 'react';
import { Form, useActionData, useNavigation } from '@remix-run/react';
import type { ActionFunction, LoaderFunction } from '@remix-run/node';
import { json, redirect } from '@remix-run/node';
import { prisma } from '~/utils/db.server';
import { createUserSession, getUserFromSession, verifyPassword } from '~/utils/session.server';

export const loader: LoaderFunction = async ({ request }) => {
  const user = await getUserFromSession(request);
  if (user) return redirect('/');
  return json({});
};

export const action: ActionFunction = async ({ request }) => {
  const formData = await request.formData();
  const username = formData.get('username') as string;
  const password = formData.get('password') as string;

  if (!username || !password) {
    return json({ error: '请输入用户名和密码' }, { status: 400 });
  }

  const user = await prisma.user.findUnique({ where: { username } });
  if (!user) {
    return json({ error: '用户名或密码错误' }, { status: 400 });
  }

  const isValid = await verifyPassword(password, user.password);
  if (!isValid) {
    return json({ error: '用户名或密码错误' }, { status: 400 });
  }

  return createUserSession(user.id, '/');
};

export default function Login() {
  const actionData = useActionData<typeof action>();
  const navigation = useNavigation();
  const isLoading = navigation.state === 'submitting';

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-red-600 to-red-800">
      <div className="bg-white p-8 rounded-lg shadow-2xl w-full max-w-md">
        <div className="text-center mb-8">
          <div className="text-5xl mb-4">🔥</div>
          <h1 className="text-2xl font-bold text-gray-800">消防隐患巡检系统</h1>
          <p className="text-gray-500 mt-2">请登录您的账户</p>
        </div>

        {actionData?.error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded mb-4">
            {actionData.error}
          </div>
        )}

        <Form method="post" className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              用户名
            </label>
            <input
              type="text"
              name="username"
              required
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-transparent"
              placeholder="请输入用户名"
              disabled={isLoading}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              密码
            </label>
            <input
              type="password"
              name="password"
              required
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-transparent"
              placeholder="请输入密码"
              disabled={isLoading}
            />
          </div>

          <button
            type="submit"
            disabled={isLoading}
            className="w-full bg-red-600 hover:bg-red-700 text-white font-semibold py-3 px-4 rounded-lg transition duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isLoading ? '登录中...' : '登 录'}
          </button>
        </Form>

        <div className="mt-6 p-4 bg-gray-50 rounded-lg">
          <p className="text-sm text-gray-600 font-medium mb-2">测试账号：</p>
          <div className="text-xs text-gray-500 space-y-1">
            <p>巡检员: inspector / 123456</p>
            <p>物业经办人: property / 123456</p>
            <p>消防复核人: fire / 123456</p>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';

	let email = 'consultant@example.com';
	let password = 'password123';
	let error = '';
	let loading = false;

	async function login() {
		error = '';
		loading = true;

		try {
			const res = await fetch('/api/login', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ email, password })
			});

			const data = await res.json();

			if (res.ok) {
				goto('/');
			} else {
				error = data.error;
			}
		} catch (e) {
			error = '登录失败，请重试';
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-700 to-slate-900">
	<div class="bg-white p-8 rounded-lg shadow-xl w-full max-w-md">
		<h1 class="text-2xl font-bold text-center text-slate-800 mb-8">试听课预约与转化回访系统</h1>

		{#if error}
			<div class="bg-red-50 text-red-600 p-3 rounded mb-4 text-sm">{error}</div>
		{/if}

		<form on:submit|preventDefault={login} class="space-y-4">
			<div>
				<label class="block text-sm font-medium text-slate-700 mb-1">邮箱</label>
				<input
					type="email"
					bind:value={email}
					class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					placeholder="请输入邮箱"
					required
				/>
			</div>

			<div>
				<label class="block text-sm font-medium text-slate-700 mb-1">密码</label>
				<input
					type="password"
					bind:value={password}
					class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					placeholder="请输入密码"
					required
				/>
			</div>

			<button
				type="submit"
				disabled={loading}
				class="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
			>
				{loading ? '登录中...' : '登录'}
			</button>
		</form>

		<div class="mt-6 text-sm text-slate-500 space-y-1">
			<p class="font-medium text-slate-600">测试账号：</p>
			<p>顾问：consultant@example.com / password123</p>
			<p>教务：admin@example.com / password123</p>
			<p>主管：supervisor@example.com / password123</p>
		</div>
	</div>
</div>

<style>
	form {
		font-family: system-ui, -apple-system, sans-serif;
	}
</style>
